version: '2'
services:
  convergence_monitor_front_end-postgresql:
    image: postgres:12.3
    # volumes:
    #     - ~/volumes/jhipster/convergence_monitor_front_end/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=convergence_monitor_front_end
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
